# Generated by Django 4.2.10 on 2024-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='lugar',
            field=models.CharField(default='urubamba', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital',
            field=models.CharField(default='Hosp. I Urubamba', max_length=20),
        ),
    ]
