# Generated by Django 4.2.10 on 2024-02-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_hospital_lugar_alter_hospital_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekg',
            name='observacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(default='xxxxx', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='lugar',
            field=models.CharField(default='Urubamba', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pie',
            name='observacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='observacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
